/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import business_layer.ClassBusiness;
import business_layer.StudentBusiness;
import business_layer.TeacherBusiness;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.ClassModel;
import model.StudentModel;
import model.TeacherModel;
import org.apache.commons.lang3.StringUtils;

/**
 * ClassManageForm
 */
public class ClassManageForm extends javax.swing.JInternalFrame {

    private final StudentBusiness studentBS = new StudentBusiness();

    private final ClassBusiness classBS = new ClassBusiness();

    private final TeacherBusiness teacherBS = new TeacherBusiness();

    // List of classes in table
    private List<ClassModel> classes;

    private DefaultTableModel dtm;

    /**
     * Creates new form ClassManageForm
     */
    public ClassManageForm() {
        initComponents();
        this.setFrameIcon(new ImageIcon(""));

        // Load info of class
        classes = classBS.getAll();
        loadClassInfo();
        // Load monitor in combobox
        loadMonitorID();
        // Load teacher in combobox
        loadTeacherID();
        // Load header of student in class table
        loadStudentInClass("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClass = new javax.swing.JTable();
        txtSearchClass = new javax.swing.JTextField();
        btnSearchClass = new javax.swing.JButton();
        btnEditClass = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();
        btnResetClass = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        cbbMonitor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbTeacher = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStudentInClass = new javax.swing.JTable();

        setTitle("Quản lý lớp");
        setVisible(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin lớp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        tbClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClass);

        btnSearchClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/find.png"))); // NOI18N
        btnSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClassActionPerformed(evt);
            }
        });

        btnEditClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/edit.png"))); // NOI18N
        btnEditClass.setText("Cập nhật");
        btnEditClass.setEnabled(false);
        btnEditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClassActionPerformed(evt);
            }
        });

        btnDeleteClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/cancel.png"))); // NOI18N
        btnDeleteClass.setText("Xóa");
        btnDeleteClass.setEnabled(false);
        btnDeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClassActionPerformed(evt);
            }
        });

        btnResetClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnResetClass.setText("Reset");
        btnResetClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetClassActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã lớp:");

        txtClassID.setEditable(false);

        jLabel4.setText("Tên lớp:");

        jLabel6.setText("Sỉ số:");

        jLabel7.setText("Lớp trưởng:");

        cbbMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel8.setText("Khóa học:");

        jLabel5.setText("GVCN:");

        cbbTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtClassID)
                                    .addComponent(txtMember, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchClass))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnEditClass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnResetClass, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchClass)
                    .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditClass)
                    .addComponent(btnDeleteClass)
                    .addComponent(btnResetClass))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbbTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách sinh viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        tbStudentInClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbStudentInClass);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClassMouseClicked
        int row = tbClass.getSelectedRow();
        ClassModel selectedClass = classes.get(row);
        txtClassID.setText(selectedClass.getId());
        txtClassName.setText(selectedClass.getName());
        txtCourse.setText(selectedClass.getCourse());
        txtMember.setText(String.valueOf(selectedClass.getNumberOfStudent()));
        cbbMonitor.setSelectedItem(selectedClass.getMonitor());
        cbbTeacher.setSelectedItem(selectedClass.getTeacher());
        btnEditClass.setEnabled(true);
        btnDeleteClass.setEnabled(true);

        // Load list of students belong to selected class
        loadStudentInClass(txtClassID.getText());
    }//GEN-LAST:event_tbClassMouseClicked

    private void btnSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClassActionPerformed
        String key = txtSearchClass.getText();
        classes = classBS.searchClass(key);
        loadClassInfo();
        btnEditClass.setEnabled(false);
        btnDeleteClass.setEnabled(false);
        txtClassID.setText("");
        txtClassName.setText("");
        txtCourse.setText("");
        txtMember.setText("");
        cbbMonitor.setSelectedIndex(0);
        cbbTeacher.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchClassActionPerformed

    private void btnEditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClassActionPerformed
        ClassModel model = new ClassModel();
        model.setId(txtClassID.getText());
        model.setName(txtClassName.getText());
        model.setCourse(txtCourse.getText());
        int member;
        try {
            member = Integer.parseInt(txtMember.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Sỉ số phải là số nguyên dương", "Error", JOptionPane.ERROR_MESSAGE);
            txtMember.requestFocus();
            return;
        }
        if (member <= 0) {
            JOptionPane.showMessageDialog(this, "Sỉ số phải là số nguyên dương", "Error", JOptionPane.ERROR_MESSAGE);
            txtMember.requestFocus();
            return;
        }
        model.setNumberOfStudent(member);
        if (cbbMonitor.getSelectedIndex() > 0) {
            model.setMonitor(cbbMonitor.getSelectedItem().toString());
        }
        if (cbbTeacher.getSelectedIndex() > 0) {
            model.setTeacher(cbbTeacher.getSelectedItem().toString());
        }

        int row = classBS.update(model);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Update thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            classes = classBS.getAll();
            loadClassInfo();
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditClassActionPerformed

    private void btnDeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClassActionPerformed
        String classID = txtClassID.getText();
        int row = classBS.delete(classID);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Delete thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetClass();
        } else {
            JOptionPane.showMessageDialog(this, "Delete thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteClassActionPerformed

    private void btnResetClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetClassActionPerformed
        resetClass();
    }//GEN-LAST:event_btnResetClassActionPerformed

    private void resetClass() {
        txtSearchClass.setText("");
        btnEditClass.setEnabled(false);
        btnDeleteClass.setEnabled(false);
        txtClassID.setText("");
        txtClassName.setText("");
        txtCourse.setText("");
        txtMember.setText("");
        cbbMonitor.setSelectedIndex(0);
        cbbTeacher.setSelectedIndex(0);
        classes = classBS.getAll();
        loadClassInfo();
        loadStudentInClass("");
    }

    // Load list of students belong to the specific class
    private void loadStudentInClass(String classID) {
        Vector<String> columns = new Vector<>();
        columns.add("Mã SV");
        columns.add("Họ Tên");

        Vector<Vector> datas = new Vector<>();
        List<StudentModel> students = studentBS.getStudentsInClass(classID);
        for (StudentModel student : students) {
            Vector rows = new Vector();
            rows.add(student.getId());
            rows.add(student.getName());
            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbStudentInClass.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbStudentInClass.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(120);
    }

    // Load info of class
    private void loadClassInfo() {
        Vector<String> columns = new Vector<>();
        columns.add("Mã Lớp");
        columns.add("Tên Lớp");
        columns.add("Khóa Học");
        columns.add("Sĩ Số");
        columns.add("Lớp Trưởng");
        columns.add("GVCN");

        Vector<Vector> datas = new Vector<>();
        for (ClassModel model : classes) {
            Vector rows = new Vector();
            rows.add(model.getId());
            rows.add(model.getName());
            rows.add(model.getCourse());
            rows.add(model.getNumberOfStudent());
            if (!StringUtils.isBlank(model.getMonitor())) {
                StudentModel student = studentBS.getStudentByID(model.getMonitor());
                if (student != null) {
                    rows.add(student.getName());
                } else {
                    rows.add("");
                }
            } else {
                rows.add("");
            }
            if (!StringUtils.isBlank(model.getTeacher())) {
                TeacherModel teacher = teacherBS.getByID(model.getTeacher());
                if (teacher != null) {
                    rows.add(teacher.getName());
                } else {
                    rows.add("");
                }
            } else {
                rows.add("");
            }
            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbClass.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbClass.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(30);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);

    }

    private void loadMonitorID() {
        List<String> ids = studentBS.getIDs();
        ids.forEach(item -> cbbMonitor.addItem(item));
    }

    private void loadTeacherID() {
        List<String> ids = teacherBS.getIDs();
        ids.forEach(item -> cbbTeacher.addItem(item));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnEditClass;
    private javax.swing.JButton btnResetClass;
    private javax.swing.JButton btnSearchClass;
    private javax.swing.JComboBox<String> cbbMonitor;
    private javax.swing.JComboBox<String> cbbTeacher;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbClass;
    private javax.swing.JTable tbStudentInClass;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextField txtSearchClass;
    // End of variables declaration//GEN-END:variables

}
