/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import business_layer.ClassBusiness;
import business_layer.StudentBusiness;
import business_layer.TeacherBusiness;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.ClassModel;
import model.StudentModel;
import model.TeacherModel;
import org.apache.commons.lang3.StringUtils;

/**
 * ClassInfoForm
 */
public class ClassInfoForm extends javax.swing.JInternalFrame {

    private final ClassBusiness classBS = new ClassBusiness();

    private final StudentBusiness studentBS = new StudentBusiness();

    private final TeacherBusiness teacherBS = new TeacherBusiness();

    private DefaultTableModel dtm;

    /**
     * Creates new form ClassInfoForm
     */
    public ClassInfoForm() {
        initComponents();
        this.setFrameIcon(new ImageIcon(""));

        // Load class info
        List<ClassModel> list = classBS.getAll();
        loadClassInfo(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbClass = new javax.swing.JTable();
        txtSearchClass = new javax.swing.JTextField();
        btnSearchClass = new javax.swing.JButton();
        btnResetClass = new javax.swing.JButton();

        setTitle("Thông tin lớp");
        setVisible(true);

        tbClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbClass);

        btnSearchClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/find.png"))); // NOI18N
        btnSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClassActionPerformed(evt);
            }
        });

        btnResetClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnResetClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetClass)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClass)
                    .addComponent(btnResetClass))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClassActionPerformed
        String key = txtSearchClass.getText();
        List<ClassModel> list = classBS.searchClass(key);
        loadClassInfo(list);
    }//GEN-LAST:event_btnSearchClassActionPerformed

    private void btnResetClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetClassActionPerformed
        txtSearchClass.setText("");
        List<ClassModel> list = classBS.getAll();
        loadClassInfo(list);
    }//GEN-LAST:event_btnResetClassActionPerformed

    // Load info of class
    private void loadClassInfo(List<ClassModel> list) {
        Vector<String> columns = new Vector<>();
        columns.add("Mã Lớp");
        columns.add("Tên Lớp");
        columns.add("Khóa Học");
        columns.add("Sĩ Số");
        columns.add("Lớp Trưởng");
        columns.add("GVCN");

        Vector<Vector> datas = new Vector<>();
        for (ClassModel model : list) {
            Vector rows = new Vector();
            rows.add(model.getId());
            rows.add(model.getName());
            rows.add(model.getCourse());
            rows.add(model.getNumberOfStudent());
            if (!StringUtils.isBlank(model.getMonitor())) {
                StudentModel student = studentBS.getStudentByID(model.getMonitor());
                if (student != null) {
                    model.setMonitor(student.getName());
                } else {
                    rows.add("");
                }
            } else {
                rows.add("");
            }
            rows.add(model.getMonitor());
            if (!StringUtils.isBlank(model.getTeacher())) {
                TeacherModel teacher = teacherBS.getByID(model.getTeacher());
                if (teacher != null) {
                    model.setTeacher(teacher.getName());
                } else {
                    rows.add("");
                }
            } else {
                rows.add("");
            }
            rows.add(model.getTeacher());
            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbClass.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbClass.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(30);
        columnModel.getColumn(4).setPreferredWidth(150);
        columnModel.getColumn(5).setPreferredWidth(150);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetClass;
    private javax.swing.JButton btnSearchClass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClass;
    private javax.swing.JTextField txtSearchClass;
    // End of variables declaration//GEN-END:variables
}
