/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 * ManagerForm
 */
public class ManagerForm extends javax.swing.JFrame {

    private String account;

    private String password;

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public JLabel getLbUserName() {
        return lbUserName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        classManageItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        studentManageItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        scoreAndConductItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        teacherManageItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        orderClassItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        changePWItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        grantItem = new javax.swing.JPopupMenu.Separator();
        logOutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setLocation(new java.awt.Point(100, 40));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Quản lý sinh viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Xin chào");

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserName.setText("user name");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Tác vụ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        classManageItem.setText("Quản lý lớp");
        classManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classManageItemActionPerformed(evt);
            }
        });
        jMenu1.add(classManageItem);
        jMenu1.add(jSeparator2);

        studentManageItem.setText("Quản lý sinh viên");
        studentManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManageItemActionPerformed(evt);
            }
        });
        jMenu1.add(studentManageItem);
        jMenu1.add(jSeparator3);

        scoreAndConductItem.setText("Xem điểm, hạnh kiểm");
        scoreAndConductItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreAndConductItemActionPerformed(evt);
            }
        });
        jMenu1.add(scoreAndConductItem);
        jMenu1.add(jSeparator4);

        teacherManageItem.setText("Quản lý giảng viên");
        teacherManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherManageItemActionPerformed(evt);
            }
        });
        jMenu1.add(teacherManageItem);
        jMenu1.add(jSeparator5);

        orderClassItem.setText("Quản lý xếp lớp");
        orderClassItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderClassItemActionPerformed(evt);
            }
        });
        jMenu1.add(orderClassItem);
        jMenu1.add(jSeparator6);

        jMenuItem2.setText("Xét điều kiện làm luận văn, thi tốt nghiệp");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator7);

        jMenuItem3.setText("Xét điều kiện ra trường, xếp loại tốt nghiệp");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tài khoản");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        changePWItem.setText("Đổi mật khẩu");
        changePWItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePWItemActionPerformed(evt);
            }
        });
        jMenu2.add(changePWItem);
        jMenu2.add(jSeparator1);

        jMenuItem1.setText("Ủy quyền sử dụng");
        jMenu2.add(jMenuItem1);
        jMenu2.add(grantItem);

        logOutItem.setText("Đăng xuất");
        logOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutItemActionPerformed(evt);
            }
        });
        jMenu2.add(logOutItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(984, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(510, 510, 510))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutItemActionPerformed
        this.setVisible(false);
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_logOutItemActionPerformed

    private void changePWItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePWItemActionPerformed
        ChangePWForm changeFrom = new ChangePWForm();
        changeFrom.setCurrentAccount(account);
        changeFrom.setCurrentPassword(password);
        changeFrom.setManageForm(this);
        changeFrom.setVisible(true);
    }//GEN-LAST:event_changePWItemActionPerformed

    private void classManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classManageItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        ClassManageForm classManageForm = new ClassManageForm();
        desktopPane.add(classManageForm);
        try {
            classManageForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classManageItemActionPerformed

    private void studentManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManageItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        StudentManageForm studentManageForm = new StudentManageForm();
        desktopPane.add(studentManageForm);
        try {
            studentManageForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentManageItemActionPerformed

    private void scoreAndConductItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreAndConductItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        ScoreConductManageForm scoreConductForm = new ScoreConductManageForm();
        desktopPane.add(scoreConductForm);
        try {
            scoreConductForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scoreAndConductItemActionPerformed

    private void teacherManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherManageItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        TeacherManageForm teacherManageForm = new TeacherManageForm();
        desktopPane.add(teacherManageForm);
        try {
            teacherManageForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_teacherManageItemActionPerformed

    private void orderClassItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderClassItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        OrderClassForm orderClassForm = new OrderClassForm();
        desktopPane.add(orderClassForm);
        try {
            orderClassForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_orderClassItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        Form2 form2 = new Form2();
        desktopPane.add(form2);
        try {
            form2.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        Form3 form3 = new Form3();
        desktopPane.add(form3);
        try {
            form3.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changePWItem;
    private javax.swing.JMenuItem classManageItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator grantItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JMenuItem logOutItem;
    private javax.swing.JMenuItem orderClassItem;
    private javax.swing.JMenuItem scoreAndConductItem;
    private javax.swing.JMenuItem studentManageItem;
    private javax.swing.JMenuItem teacherManageItem;
    // End of variables declaration//GEN-END:variables
}
