/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import business_layer.ClassBusiness;
import business_layer.ExcelService;
import business_layer.StudentBusiness;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.ChangeClassModel;
import model.ClassModel;
import model.RewardModel;
import model.StudentModel;
import org.apache.commons.lang3.StringUtils;

/**
 * StudentManageForm
 */
public class StudentManageForm extends javax.swing.JInternalFrame {

    private static final String DATE_FORMAT = "yyyy/MM/dd";

    private final StudentBusiness studentBS = new StudentBusiness();

    private final ClassBusiness classBS = new ClassBusiness();

    private final ExcelService excelService = new ExcelService();

    private DefaultTableModel dtm;

    // List of students in table
    private List<StudentModel> students;

    /**
     * Creates new form StudentManageForm
     */
    public StudentManageForm() {
        initComponents();
        this.setFrameIcon(new ImageIcon(""));

        // Load student info
        students = studentBS.getAll();
        loadStudentInfo();
        // Load rewards info
        loadRewards();
        // Load student IDs
        loadStudentID();
        // Load change class info
        loadChangeClass();
// Load class ID
        loadClassID();
        // Format date chooser
        dcStudentBirthday.setDateFormatString(DATE_FORMAT);
        dcInDate.setDateFormatString(DATE_FORMAT);
        dcOutDate.setDateFormatString(DATE_FORMAT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        txtSearchStudent = new javax.swing.JTextField();
        btnSearchStudent = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnResetStudent = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dcStudentBirthday = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cbbStudentGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtStudentEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtStudentAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStudentPOB = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtStudentPhone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbbStudentClass = new javax.swing.JComboBox<>();
        btnExportStudent = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbReward = new javax.swing.JTable();
        btnAddReward = new javax.swing.JButton();
        btnEditReward = new javax.swing.JButton();
        btnDeleteReward = new javax.swing.JButton();
        btnResetReward = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbbRewardStudentID = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbbRewardType = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtRewardContent = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRewardReason = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbChangeClass = new javax.swing.JTable();
        btnAddChangeClass = new javax.swing.JButton();
        btnEditChangeClass = new javax.swing.JButton();
        btnDeleteChangeClass = new javax.swing.JButton();
        btnResetChangeClass = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbbChangeStudentID = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cbbChangeClassID = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dcInDate = new com.toedter.calendar.JDateChooser();
        dcOutDate = new com.toedter.calendar.JDateChooser();

        setTitle("Quản lý sinh viên");
        setVisible(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin sinh viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbStudent);

        btnSearchStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/find.png"))); // NOI18N
        btnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentActionPerformed(evt);
            }
        });

        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/add.png"))); // NOI18N
        btnAddStudent.setText("Thêm");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/edit.png"))); // NOI18N
        btnEditStudent.setText("Cập nhật");
        btnEditStudent.setEnabled(false);
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/cancel.png"))); // NOI18N
        btnDeleteStudent.setText("Xóa");
        btnDeleteStudent.setEnabled(false);
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnResetStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnResetStudent.setText("Reset");
        btnResetStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetStudentActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã SV:");

        jLabel10.setText("Họ tên:");

        jLabel11.setText("Ngày sinh:");

        jLabel12.setText("Giới tính:");

        cbbStudentGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));
        cbbStudentGender.setSelectedItem(null);

        jLabel14.setText("Email:");

        jLabel15.setText("Địa chỉ:");

        jLabel16.setText("Nơi sinh:");

        jLabel18.setText("ĐT:");

        txtStudentPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPhoneActionPerformed(evt);
            }
        });

        jLabel13.setText("Lớp:");

        cbbStudentClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnExportStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/excel.png"))); // NOI18N
        btnExportStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentPOB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbStudentClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcStudentBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchStudent)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchStudent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddStudent)
                            .addComponent(btnEditStudent)
                            .addComponent(btnDeleteStudent)
                            .addComponent(btnResetStudent))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dcStudentBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cbbStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(txtStudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtStudentPOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbbStudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý thưởng, phạt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        tbReward.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbReward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRewardMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbReward);

        btnAddReward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/add.png"))); // NOI18N
        btnAddReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRewardActionPerformed(evt);
            }
        });

        btnEditReward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/edit.png"))); // NOI18N
        btnEditReward.setEnabled(false);
        btnEditReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRewardActionPerformed(evt);
            }
        });

        btnDeleteReward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/cancel.png"))); // NOI18N
        btnDeleteReward.setEnabled(false);
        btnDeleteReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRewardActionPerformed(evt);
            }
        });

        btnResetReward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnResetReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetRewardActionPerformed(evt);
            }
        });

        jLabel17.setText("Mã SV:");

        jLabel19.setText("Loại:");

        cbbRewardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Thưởng", "Phạt" }));

        jLabel20.setText("Nội dung:");

        jLabel21.setText("Lý do:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAddReward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditReward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteReward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetReward)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbRewardStudentID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbRewardType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRewardContent)
                            .addComponent(txtRewardReason))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddReward)
                    .addComponent(btnEditReward)
                    .addComponent(btnDeleteReward)
                    .addComponent(btnResetReward))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbbRewardStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtRewardContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbbRewardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtRewardReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chuyển lớp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        tbChangeClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbChangeClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChangeClassMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbChangeClass);

        btnAddChangeClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/add.png"))); // NOI18N
        btnAddChangeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChangeClassActionPerformed(evt);
            }
        });

        btnEditChangeClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/edit.png"))); // NOI18N
        btnEditChangeClass.setEnabled(false);
        btnEditChangeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditChangeClassActionPerformed(evt);
            }
        });

        btnDeleteChangeClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/cancel.png"))); // NOI18N
        btnDeleteChangeClass.setEnabled(false);
        btnDeleteChangeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteChangeClassActionPerformed(evt);
            }
        });

        btnResetChangeClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnResetChangeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetChangeClassActionPerformed(evt);
            }
        });

        jLabel22.setText("Mã SV:");

        cbbChangeStudentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel23.setText("Mã lớp:");

        cbbChangeClassID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel24.setText("Ngày đến:");

        jLabel25.setText("Ngày đi:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnAddChangeClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditChangeClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteChangeClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetChangeClass))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbChangeStudentID, 0, 73, Short.MAX_VALUE)
                            .addComponent(cbbChangeClassID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcInDate, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(dcOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddChangeClass)
                    .addComponent(btnEditChangeClass)
                    .addComponent(btnDeleteChangeClass)
                    .addComponent(btnResetChangeClass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(cbbChangeStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(dcInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(cbbChangeClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked
        int row = tbStudent.getSelectedRow();
        StudentModel student = students.get(row);
        txtStudentID.setText(student.getId());
        txtStudentName.setText(student.getName());
        dcStudentBirthday.setDate(student.getBirthday());
        cbbStudentGender.setSelectedIndex(student.getGender());
        txtStudentPhone.setText(student.getPhoneNumber());
        txtStudentEmail.setText(student.getEmail());
        txtStudentAddress.setText(student.getAddress());
        txtStudentPOB.setText(student.getPlaceOfBirth());
        cbbStudentClass.setSelectedItem(student.getClassID());

        // Enable button
        btnEditStudent.setEnabled(true);
        btnDeleteStudent.setEnabled(true);
    }//GEN-LAST:event_tbStudentMouseClicked

    private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentActionPerformed
        String studentID = txtSearchStudent.getText();
        students = studentBS.searchStudent(studentID);
        loadStudentInfo();
        txtStudentID.setText("");
        txtStudentName.setText("");
        dcStudentBirthday.setDate(null);
        cbbStudentGender.setSelectedIndex(-1);
        txtStudentPhone.setText("");
        txtStudentEmail.setText("");
        txtStudentAddress.setText("");
        txtStudentPOB.setText("");
        cbbStudentClass.setSelectedIndex(0);
        btnEditStudent.setEnabled(false);
        btnDeleteStudent.setEnabled(false);
    }//GEN-LAST:event_btnSearchStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        String studentID = txtStudentID.getText();
        // Check student ID is blank
        if (StringUtils.isBlank(studentID)) {
            JOptionPane.showMessageDialog(null, "Mã SV không thể rỗng");
            txtStudentID.requestFocus();
            return;
        }

        // Check student ID is duplicate
        StudentModel model = studentBS.getStudentByID(studentID);
        if (model != null) {
            JOptionPane.showMessageDialog(null, "Mã SV đã tồn tại, vui lòng nhập mã khác");
            txtStudentID.requestFocus();
            return;
        }

        // Check format of birthdate inputed
        if (!StringUtils.equals(DATE_FORMAT, dcStudentBirthday.getDateFormatString())) {
            JOptionPane.showMessageDialog(null, "Ngày sinh sai format (Format đúng: yyyy/MM/dd)");
            dcStudentBirthday.requestFocus();
            return;
        }
        StudentModel student = new StudentModel();
        student.setId(studentID);
        student.setName(txtStudentName.getText());
        student.setBirthday(dcStudentBirthday.getDate());
        student.setGender(cbbStudentGender.getSelectedIndex());
        student.setPhoneNumber(txtStudentPhone.getText());
        student.setEmail(txtStudentEmail.getText());
        student.setAddress(txtStudentAddress.getText());
        student.setPlaceOfBirth(txtStudentPOB.getText());
        if (cbbStudentClass.getSelectedIndex() > 0) {
            student.setClassID(cbbStudentClass.getSelectedItem().toString());
        }

        int row = studentBS.insert(student);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Insert thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetStudent();
        } else {
            JOptionPane.showMessageDialog(this, "Insert thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        StudentModel student = new StudentModel();
        student.setId(txtStudentID.getText());
        student.setName(txtStudentName.getText());
        student.setBirthday(dcStudentBirthday.getDate());
        student.setGender(cbbStudentGender.getSelectedIndex());
        student.setPhoneNumber(txtStudentPhone.getText());
        student.setEmail(txtStudentEmail.getText());
        student.setAddress(txtStudentAddress.getText());
        student.setPlaceOfBirth(txtStudentPOB.getText());
        if (cbbStudentClass.getSelectedIndex() > 0) {
            student.setClassID(cbbStudentClass.getSelectedItem().toString());
        }

        int row = studentBS.update(student);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Update thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            students = studentBS.getAll();
            loadStudentInfo();
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        String studentID = txtStudentID.getText();
        int row = studentBS.delete(studentID);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Delete thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetStudent();
        } else {
            JOptionPane.showMessageDialog(this, "Delete thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnResetStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetStudentActionPerformed
        resetStudent();
    }//GEN-LAST:event_btnResetStudentActionPerformed

    private void txtStudentPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentPhoneActionPerformed

    private void btnExportStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportStudentActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int r = fileChooser.showOpenDialog(null);
        String file = "SinhVien.xlsx";
        if (r == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (StringUtils.endsWith(path, "\\")) {
                file = path + file;
            } else {
                file = path + "\\" + file;
            }

            List<List<Object>> listStudent = new ArrayList<>();
            for (int i = 0; i < tbStudent.getRowCount(); i++) {
                List<Object> student = new ArrayList<>();
                student.add(tbStudent.getValueAt(i, 0));
                student.add(tbStudent.getValueAt(i, 1));
                student.add(tbStudent.getValueAt(i, 2));
                student.add(tbStudent.getValueAt(i, 3));
                student.add(tbStudent.getValueAt(i, 4));
                student.add(tbStudent.getValueAt(i, 5));
                student.add(tbStudent.getValueAt(i, 6));
                student.add(tbStudent.getValueAt(i, 7));
                student.add(tbStudent.getValueAt(i, 8));
                listStudent.add(student);
            }
            boolean isExported = excelService.exportStudent(file, listStudent);
            if (isExported) {
                JOptionPane.showMessageDialog(this, "Export excel thành công: " + file,
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Export excel thất bại!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportStudentActionPerformed

    private void tbRewardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRewardMouseClicked
        int row = tbReward.getSelectedRow();
        List<RewardModel> rewards = studentBS.getAllRewards();
        RewardModel reward = rewards.get(row);
        cbbRewardStudentID.setSelectedItem(reward.getStudentID());
        cbbRewardType.setSelectedIndex(reward.getRewardType());
        txtRewardContent.setText(reward.getContent());
        txtRewardReason.setText(reward.getReason());
        btnEditReward.setEnabled(true);
        btnDeleteReward.setEnabled(true);
    }//GEN-LAST:event_tbRewardMouseClicked

    private void btnAddRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRewardActionPerformed
        if (cbbRewardStudentID.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã SV");
            return;
        }

        RewardModel reward = new RewardModel();
        reward.setStudentID(cbbRewardStudentID.getSelectedItem().toString());
        reward.setRewardType(cbbRewardType.getSelectedIndex());
        reward.setContent(txtRewardContent.getText());
        reward.setReason(txtRewardReason.getText());

        int row = studentBS.insertReward(reward);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Insert thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            loadRewards();
        } else {
            JOptionPane.showMessageDialog(this, "Insert thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddRewardActionPerformed

    private void btnEditRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRewardActionPerformed
        if (cbbRewardStudentID.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã SV");
            return;
        }

        int rowSelected = tbReward.getSelectedRow();
        RewardModel reward = studentBS.getAllRewards().get(rowSelected);
        reward.setStudentID(cbbRewardStudentID.getSelectedItem().toString());
        reward.setRewardType(cbbRewardType.getSelectedIndex());
        reward.setContent(txtRewardContent.getText());
        reward.setReason(txtRewardReason.getText());

        int row = studentBS.updateReward(reward);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Update thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetReward();
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditRewardActionPerformed

    private void btnDeleteRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRewardActionPerformed
        int rowSelected = tbReward.getSelectedRow();
        RewardModel reward = studentBS.getAllRewards().get(rowSelected);

        int row = studentBS.deleteReward(reward.getId());
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Delete thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetReward();
        } else {
            JOptionPane.showMessageDialog(this, "Delete thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteRewardActionPerformed

    private void btnResetRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRewardActionPerformed
        resetReward();
    }//GEN-LAST:event_btnResetRewardActionPerformed

    private void tbChangeClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChangeClassMouseClicked
        int row = tbChangeClass.getSelectedRow();
        ChangeClassModel model = studentBS.getAllChangeClass().get(row);
        cbbChangeStudentID.setSelectedItem(model.getStudentID());
        cbbChangeClassID.setSelectedItem(model.getClassID());
        dcInDate.setDate(model.getInDate());
        dcOutDate.setDate(model.getOutDate());
        btnEditChangeClass.setEnabled(true);
        btnDeleteChangeClass.setEnabled(true);
    }//GEN-LAST:event_tbChangeClassMouseClicked

    private void btnAddChangeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChangeClassActionPerformed
        if (cbbChangeStudentID.getSelectedIndex() <= 0 || cbbChangeClassID.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã SV và Mã Lớp");
            return;
        }

        ChangeClassModel model = new ChangeClassModel();
        model.setStudentID(cbbChangeStudentID.getSelectedItem().toString());
        model.setClassID(cbbChangeClassID.getSelectedItem().toString());
        model.setInDate(dcInDate.getDate());
        model.setOutDate(dcOutDate.getDate());

        int row = studentBS.insertChangeClass(model);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Insert thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            loadChangeClass();
        } else {
            JOptionPane.showMessageDialog(this, "Insert thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddChangeClassActionPerformed

    private void btnEditChangeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditChangeClassActionPerformed
        if (cbbChangeStudentID.getSelectedIndex() <= 0 || cbbChangeClassID.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã SV và Mã Lớp");
            return;
        }

        int rowSelected = tbChangeClass.getSelectedRow();
        ChangeClassModel model = studentBS.getAllChangeClass().get(rowSelected);
        model.setStudentID(cbbChangeStudentID.getSelectedItem().toString());
        model.setClassID(cbbChangeClassID.getSelectedItem().toString());
        model.setInDate(dcInDate.getDate());
        model.setOutDate(dcOutDate.getDate());

        int row = studentBS.updateChangeClass(model);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Update thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetChangeClass();
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditChangeClassActionPerformed

    private void btnDeleteChangeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteChangeClassActionPerformed
        int rowSelected = tbChangeClass.getSelectedRow();
        ChangeClassModel model = studentBS.getAllChangeClass().get(rowSelected);

        int row = studentBS.deleteChangeClass(model.getId());
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Delete thành công!", "Info", JOptionPane.INFORMATION_MESSAGE);
            resetChangeClass();
        } else {
            JOptionPane.showMessageDialog(this, "Delete thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteChangeClassActionPerformed

    private void btnResetChangeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetChangeClassActionPerformed
        resetChangeClass();
    }//GEN-LAST:event_btnResetChangeClassActionPerformed

    private void resetChangeClass() {
        btnEditChangeClass.setEnabled(false);
        btnDeleteChangeClass.setEnabled(false);
        cbbChangeStudentID.setSelectedIndex(0);
        cbbChangeClassID.setSelectedIndex(0);
        dcInDate.setDate(null);
        dcOutDate.setDate(null);
        loadChangeClass();
    }

    private void resetReward() {
        btnEditReward.setEnabled(false);
        btnDeleteReward.setEnabled(false);
        cbbRewardStudentID.setSelectedIndex(0);
        cbbRewardType.setSelectedIndex(0);
        txtRewardContent.setText("");
        txtRewardReason.setText("");
        loadRewards();
    }

    private void resetStudent() {
        txtSearchStudent.setText("");
        btnEditStudent.setEnabled(false);
        btnDeleteStudent.setEnabled(false);
        txtStudentID.setText("");
        txtStudentName.setText("");
        dcStudentBirthday.setDate(null);
        cbbStudentGender.setSelectedIndex(-1);
        txtStudentPhone.setText("");
        txtStudentEmail.setText("");
        txtStudentAddress.setText("");
        txtStudentPOB.setText("");
        cbbStudentClass.setSelectedIndex(0);
        students = studentBS.getAll();
        loadStudentInfo();
    }

    // Load list of students
    private void loadStudentInfo() {
        Vector<String> columns = new Vector<>();
        columns.add("Mã SV");
        columns.add("Họ Tên");
        columns.add("Ngày Sinh");
        columns.add("Giới Tính");
        columns.add("Điện Thoại");
        columns.add("Email");
        columns.add("Địa Chỉ");
        columns.add("Nơi Sinh");
        columns.add("Lớp");

        Vector<Vector> datas = new Vector<>();
        for (StudentModel student : students) {
            Vector rows = new Vector();
            rows.add(student.getId());
            rows.add(student.getName());
            rows.add(student.getBirthday());
            if (student.getGender() == 0) {
                rows.add("Nữ");
            } else {
                rows.add("Nam");
            }
            rows.add(student.getPhoneNumber());
            rows.add(student.getEmail());
            rows.add(student.getAddress());
            rows.add(student.getPlaceOfBirth());
            String className = "";
            if (!StringUtils.isBlank(student.getClassID())) {
                ClassModel classModel = classBS.getByID(student.getClassID());
                if (classModel != null) {
                    className = classModel.getName();
                }
            }
            rows.add(className);
            datas.add(rows);
        }

        dtm = new DefaultTableModel(datas, columns);
        tbStudent.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbStudent.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(80);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(4).setPreferredWidth(60);
        columnModel.getColumn(5).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(80);
        columnModel.getColumn(7).setPreferredWidth(80);
        columnModel.getColumn(8).setPreferredWidth(80);
    }

    private void loadRewards() {
        Vector<String> columns = new Vector<>();
        columns.add("Mã SV");
        columns.add("Loại");
        columns.add("Nội Dung");
        columns.add("Lý Do");

        Vector<Vector> datas = new Vector<>();
        List<RewardModel> rewards = studentBS.getAllRewards();
        for (RewardModel reward : rewards) {
            Vector rows = new Vector();
            rows.add(reward.getStudentID());
            if (reward.getRewardType() == 1) {
                rows.add("Khen thưởng");
            } else if (reward.getRewardType() == 2) {
                rows.add("Kỹ luật");
            } else {
                rows.add("");
            }
            rows.add(reward.getContent());
            rows.add(reward.getReason());

            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbReward.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbReward.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(60);
        columnModel.getColumn(2).setPreferredWidth(60);
        columnModel.getColumn(3).setPreferredWidth(60);
    }

    // Load student IDs
    private void loadStudentID() {
        List<String> ids = studentBS.getIDs();
        cbbRewardStudentID.addItem("");
        ids.forEach(item -> {
            cbbRewardStudentID.addItem(item);
            cbbChangeStudentID.addItem(item);
        });
    }

    private void loadChangeClass() {
        Vector<String> columns = new Vector<>();
        columns.add("Mã SV");
        columns.add("Mã Lớp");
        columns.add("Ngày Đến");
        columns.add("Ngày Đi");

        Vector<Vector> datas = new Vector<>();
        List<ChangeClassModel> list = studentBS.getAllChangeClass();
        for (ChangeClassModel model : list) {
            Vector rows = new Vector();
            rows.add(model.getStudentID());
            rows.add(model.getClassID());
            rows.add(model.getInDate());
            rows.add(model.getOutDate());
            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbChangeClass.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbChangeClass.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(40);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(80);
    }

    // Load class IDs
    private void loadClassID() {
        List<String> ids = classBS.getIDs();
        ids.forEach(item -> {
            cbbStudentClass.addItem(item);
            cbbChangeClassID.addItem(item);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddChangeClass;
    private javax.swing.JButton btnAddReward;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDeleteChangeClass;
    private javax.swing.JButton btnDeleteReward;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnEditChangeClass;
    private javax.swing.JButton btnEditReward;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnExportStudent;
    private javax.swing.JButton btnResetChangeClass;
    private javax.swing.JButton btnResetReward;
    private javax.swing.JButton btnResetStudent;
    private javax.swing.JButton btnSearchStudent;
    private javax.swing.JComboBox<String> cbbChangeClassID;
    private javax.swing.JComboBox<String> cbbChangeStudentID;
    private javax.swing.JComboBox<String> cbbRewardStudentID;
    private javax.swing.JComboBox<String> cbbRewardType;
    private javax.swing.JComboBox<String> cbbStudentClass;
    private javax.swing.JComboBox<String> cbbStudentGender;
    private com.toedter.calendar.JDateChooser dcInDate;
    private com.toedter.calendar.JDateChooser dcOutDate;
    private com.toedter.calendar.JDateChooser dcStudentBirthday;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbChangeClass;
    private javax.swing.JTable tbReward;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField txtRewardContent;
    private javax.swing.JTextField txtRewardReason;
    private javax.swing.JTextField txtSearchStudent;
    private javax.swing.JTextField txtStudentAddress;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentPOB;
    private javax.swing.JTextField txtStudentPhone;
    // End of variables declaration//GEN-END:variables
}
