/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import business_layer.ClassBusiness;
import business_layer.StudentBusiness;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.ClassModel;
import model.StudentModel;
import org.apache.commons.lang3.StringUtils;

/**
 * StudentInfoForm
 */
public class StudentInfoForm extends javax.swing.JInternalFrame {

    private final ClassBusiness classBS = new ClassBusiness();

    private final StudentBusiness studentBS = new StudentBusiness();

    private DefaultTableModel dtm;

    /**
     * Creates new form StudentInfoForm
     */
    public StudentInfoForm() {
        initComponents();
        this.setFrameIcon(new ImageIcon(""));

        // Load class ID
        loadClassID();
        // Load student info
        List<StudentModel> students = studentBS.getAll();
        loadStudent(students);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cbbClassID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setTitle("Thông tin sinh viên");
        setVisible(true);

        jLabel3.setText("Mã Lớp:");

        cbbClassID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbbClassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbClassIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Tìm theo mã hoặc tên");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/find.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/reset.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbClassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbClassIDActionPerformed
        if (cbbClassID.getSelectedItem() == null) {
            return;
        }
        String classID = cbbClassID.getSelectedItem().toString();
        List<StudentModel> students = studentBS.getStudentsInClass(classID);
        loadStudent(students);
    }//GEN-LAST:event_cbbClassIDActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String key = txtSearch.getText();
        List<StudentModel> students = studentBS.searchStudent(key);
        loadStudent(students);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cbbClassID.setSelectedIndex(0);
        txtSearch.setText("");
        List<StudentModel> students = studentBS.getAll();
        loadStudent(students);
    }//GEN-LAST:event_btnResetActionPerformed

    // Load all class ID
    private void loadClassID() {
        List<String> ids = classBS.getIDs();
        ids.forEach(item -> cbbClassID.addItem(item));
    }

    // Load info of student
    private void loadStudent(List<StudentModel> students) {
        Vector<String> columns = new Vector<>();
        columns.add("Mã SV");
        columns.add("Họ Tên");
        columns.add("Ngày Sinh");
        columns.add("Giới Tính");
        columns.add("Điện Thoại");
        columns.add("Email");
        columns.add("Địa Chỉ");
        columns.add("Nơi Sinh");
        columns.add("Lớp");

        Vector<Vector> datas = new Vector<>();
        for (StudentModel model : students) {
            Vector rows = new Vector();
            rows.add(model.getId());
            rows.add(model.getName());
            rows.add(model.getBirthday());
            if (model.getGender() == 0) {
                rows.add("Nữ");
            } else {
                rows.add("Nam");
            }

            rows.add(model.getPhoneNumber());
            rows.add(model.getEmail());
            rows.add(model.getAddress());
            rows.add(model.getPlaceOfBirth());
            String className = "";
            if (!StringUtils.isBlank(model.getClassID())) {
                ClassModel classModel = classBS.getByID(model.getClassID());
                if (classModel != null) {
                    className = classModel.getName();
                }
            }
            rows.add(className);

            datas.add(rows);
        }
        dtm = new DefaultTableModel(datas, columns);
        tbStudent.setModel(dtm);

        // Set size for column in the table
        TableColumnModel columnModel = tbStudent.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(30);
        columnModel.getColumn(4).setPreferredWidth(50);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(100);
        columnModel.getColumn(7).setPreferredWidth(100);
        columnModel.getColumn(8).setPreferredWidth(100);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbClassID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
