/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_layer;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 * TeacherForm
 */
public class TeacherForm extends javax.swing.JFrame {

    private String account;

    private String password;

    /**
     * Creates new form TeacherForm
     */
    public TeacherForm() {
        initComponents();
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public JLabel getLbUserName() {
        return lbUserName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        classInfoItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        studentInfoItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        scoreInfoItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        changePWItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logOutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setLocation(new java.awt.Point(100, 40));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Quản lý sinh viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Xin chào");

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserName.setText("user name");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setText("Tác vụ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        classInfoItem.setText("Thông tin lớp");
        classInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classInfoItemActionPerformed(evt);
            }
        });
        jMenu1.add(classInfoItem);
        jMenu1.add(jSeparator2);

        studentInfoItem.setText("Thông tin sinh viên");
        studentInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoItemActionPerformed(evt);
            }
        });
        jMenu1.add(studentInfoItem);
        jMenu1.add(jSeparator3);

        scoreInfoItem.setText("Thông tin điểm");
        scoreInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreInfoItemActionPerformed(evt);
            }
        });
        jMenu1.add(scoreInfoItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tài khoản");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        changePWItem.setText("Đổi mật khẩu");
        changePWItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePWItemActionPerformed(evt);
            }
        });
        jMenu2.add(changePWItem);
        jMenu2.add(jSeparator1);

        logOutItem.setText("Đăng xuất");
        logOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutItemActionPerformed(evt);
            }
        });
        jMenu2.add(logOutItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desktopPane))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(jLabel1)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void classInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classInfoItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        ClassInfoForm classForm = new ClassInfoForm();
        desktopPane.add(classForm);
        try {
            classForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classInfoItemActionPerformed

    private void studentInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        StudentInfoForm studentForm = new StudentInfoForm();
        desktopPane.add(studentForm);
        try {
            studentForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentInfoItemActionPerformed

    private void scoreInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreInfoItemActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        ScoreInfoForm scoreForm = new ScoreInfoForm();
        desktopPane.add(scoreForm);
        try {
            scoreForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scoreInfoItemActionPerformed

    private void logOutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutItemActionPerformed
        this.setVisible(false);
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_logOutItemActionPerformed

    private void changePWItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePWItemActionPerformed
        ChangePWForm changeFrom = new ChangePWForm();
        changeFrom.setCurrentAccount(account);
        changeFrom.setCurrentPassword(password);
        changeFrom.setTeacherForm(this);
        changeFrom.setVisible(true);
    }//GEN-LAST:event_changePWItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changePWItem;
    private javax.swing.JMenuItem classInfoItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JMenuItem logOutItem;
    private javax.swing.JMenuItem scoreInfoItem;
    private javax.swing.JMenuItem studentInfoItem;
    // End of variables declaration//GEN-END:variables
}
